apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-stateful.fullname" . }}-secret
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  user-password: {{ .Values.mysql.password | b64enc | quote }}