apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-stateful.fullname" . }}
  labels:
    {{- include "mysql-stateful.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "mysql-stateful.selectorLabels" . | nindent 4 }}
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306