apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-stateful.fullname" . }}
  labels:
    {{- include "mysql-stateful.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mysql-stateful.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql-stateful.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql-stateful.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-stateful.fullname" . }}-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql-stateful.fullname" . }}-secret
                  key: user-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storage.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}